// solid/src/main.tsx
import './styles/main.style.css'

import { render } from 'solid-js/web'
import { Route, Router } from '@solidjs/router'

import { NotFound } from './app/_404'
import { HomeLayout } from './app/_layout'
import { About } from './app/about'
import { AdminAbout } from './app/admin/about'
import { Admin } from './app/admin/admin'
import { Home } from './app/home'

render(
	() => (
		<Router root={HomeLayout}>
			<Route path="/" component={Home} />
			<Route path="/about" component={About} />
			<Route path="/admin" component={Admin} />
			<Route path="/admin/about" component={AdminAbout} />
			<Route path="*404" component={NotFound} />
		</Router>
	),
	document.getElementById('root')!,
)

// react/src/main.tsx
import './styles/main.style.css'

import { createRoot } from 'react-dom/client'
import { createBrowserRouter, RouteObject, RouterProvider } from 'react-router-dom'

import { Home } from './app'
import { ErrorPage } from './app/_error'
import { HomeLayout } from './app/_layout'
import { About } from './app/about'
import { Admin } from './app/admin'
import { AdminAbout } from './app/admin/about'

export const routes = [
	{
		path: '/',
		element: <HomeLayout />,
		errorElement: <ErrorPage />,
		children: [
			{ path: '/', element: <Home /> },
			{ path: '/about', element: <About /> },
			{ path: '/admin', element: <Admin /> },
			{ path: '/admin/about', element: <AdminAbout /> },
		],
	},
] satisfies RouteObject[]

createRoot(document.getElementById('root')!).render(
	// <StrictMode>
	<RouterProvider router={createBrowserRouter(routes)} />,
	// </StrictMode>,
)
