// solid/src/app/_layout.tsx
import { ParentComponent } from 'solid-js'
import { A } from '@solidjs/router'

const NAV = [
	{ label: 'Home', href: '/' },
	{ label: 'About', href: '/about' },
	{ label: 'Admin', href: '/admin' },
	{ label: 'Admin About', href: '/admin/about' },
]

export const HomeLayout: ParentComponent = (p) => {
	return (
		<div>
			<div class="flex gap-2">
				{NAV.map((route) => (
					<A activeClass="bg-red-200" href={route.href} end>
						{route.label}
					</A>
				))}
			</div>
			{p.children}
		</div>
	)
}

// react/src/app/_layout.tsx
import { NavLink, Outlet } from 'react-router'

import { routes } from '../main'

export const HomeLayout = () => {
	return (
		<div>
			<div className="flex gap-4">
				{routes[0].children?.map((route) => (
					<NavLink
						className={({ isActive }) => (isActive ? 'bg-red-200' : '')}
						key={route.path}
						to={route.path}
						end
					>
						{route.path === '/' ? 'Home' : route.path.replace('/', '')}
					</NavLink>
				))}
			</div>
			<Outlet />
		</div>
	)
}
